[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mistralai>=1.10.0",
    "pillow>=12.0.0",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.7",
    "python-dotenv>=1.0.0",
    "coloredlogs>=15.0.1",
]
